# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

      # - name: Package Mac tests
      #   run: xcodebuild test -scheme ControlCommands -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}
      # - name: Package Catalyst tests
      #   run: xcodebuild test -scheme ControlCommands -destination 'platform=macOS,variant=Mac Catalyst' | xcpretty && exit ${PIPESTATUS[0]}
      # - name: Package iPadOS tests
      #   run: xcodebuild test -scheme ControlCommands -destination 'platform=iOS Simulator,name=iPad (9th generation)' | xcpretty && exit ${PIPESTATUS[0]}
      # - name: Package iOS tests
      #   run: xcodebuild test -scheme ControlCommands -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty && exit ${PIPESTATUS[0]}

      # - name: UI Mac tests
      #   run: xcodebuild test -project TestApp/TestApp.xcodeproj -scheme TestApp -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}
      # - name: UI Catalyst tests
      #   run: xcodebuild test -project TestApp/TestApp.xcodeproj -scheme TestApp -destination 'platform=macOS,variant=Mac Catalyst' | xcpretty && exit ${PIPESTATUS[0]}
